# Generated by Django 5.1.2 on 2025-05-25 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfp', models.ImageField(blank=True, upload_to='uploads/pfp/')),
                ('course', models.CharField(choices=[('1st course', '1st course'), ('2nd course', '2nd course'), ('3th course', '3th course'), ('4th course', '4th course'), ('5th course', '5th course')], max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.groupsmodel')),
                ('owner', models.OneToOneField(limit_choices_to={'is_staff': False, 'is_teacher': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
