# Generated by Django 5.1.2 on 2025-05-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='pfp',
            field=models.ImageField(blank=True, upload_to='uploads/pfp/'),
        ),
    ]
