# Generated by Django 5.1.2 on 2025-05-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/news/'),
        ),
    ]
