# Generated by Django 5.1.2 on 2024-11-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcemodel',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
