# Generated by Django 5.1.2 on 2025-05-24 13:52

import apps.course.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
        ('professor', '0004_alter_professormodel_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.FileField(upload_to=apps.course.models.directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.groupsmodel')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.professormodel')),
            ],
        ),
    ]
