# Generated by Django 5.1.2 on 2025-05-25 12:06

import apps.course.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to=apps.course.models.directory_path)),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecontentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.ManyToManyField(blank=True, to='faculties.groupsmodel')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.professormodel')),
            ],
        ),
        migrations.AddField(
            model_name='coursecontentmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemodel'),
        ),
    ]
