# Generated by Django 5.1.2 on 2025-05-21 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('professor', '0004_alter_professormodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professor.professormodel'),
            preserve_default=False,
        ),
    ]
