# Generated by Django 5.1.2 on 2025-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursecontentmodel_course'),
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='group',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='group',
            field=models.ManyToManyField(to='faculties.groupsmodel'),
        ),
    ]
