# Generated by Django 5.1.2 on 2025-05-24 14:41

import apps.course.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_coursemodel_group_coursemodel_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontentmodel',
            name='content',
        ),
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to=apps.course.models.directory_path)),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecontentmodel')),
            ],
        ),
    ]
