# Generated by Django 5.1.2 on 2025-02-18 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100)),
                ('semester', models.CharField(choices=[('Autumn', 'Autumn'), ('Spring', 'Spring')], max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='faculties.groupsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, choices=[('10:00-11:20', '10:00-11:20'), ('11:30-12:50', '11:30-12:50'), ('13:00-14:20', '13:00-14:20'), ('15:00-16:20', '15:00-16:20'), ('16:30-17:50', '16:30-17:50'), ('18:00-19:20', '18:00-19:20')], max_length=100, null=True)),
                ('week_variance', models.CharField(blank=True, choices=[('Odd', 'Odd'), ('Even', 'Even')], max_length=100, null=True)),
                ('lesson_type', models.CharField(blank=True, choices=[('Practice', 'Practice'), ('Lecture', 'Lecture')], max_length=100, null=True)),
                ('class_room', models.CharField(max_length=200)),
                ('lesson_name', models.CharField(max_length=200)),
                ('professor', models.CharField(max_length=200)),
                ('number_of_weeks', models.CharField(max_length=50)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset', models.DateField()),
                ('end', models.DateField()),
                ('semester', models.CharField(choices=[('Autumn', 'Autumn'), ('Spring', 'Spring')], max_length=100)),
                ('course', models.CharField(choices=[('1st course', '1st course'), ('2nd course', '2nd course'), ('3th course', '3th course'), ('4th course', '4th course'), ('5th course', '5th course')], max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_schedule', to='faculties.groupsmodel')),
                ('schedules', models.ManyToManyField(related_name='semester_schedules', to='schedule.schedulemodel')),
            ],
        ),
    ]
