# Generated by Django 5.1.2 on 2025-01-27 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_group', to='faculties.groupsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('10:00-11:20', '10:00-11:20'), ('11:30-12:50', '11:30-12:50'), ('13:00-14:20', '13:00-14:20'), ('15:00-16:20', '15:00-16:20'), ('16:30-17:50', '16:30-17:50'), ('18:00-19:20', '18:00-19:20')], max_length=100)),
                ('week_variance', models.CharField(choices=[('Odd', 'Odd'), ('Even', 'Even')], max_length=100)),
                ('lesson_type', models.CharField(choices=[('Practice', 'Practice'), ('Lecture', 'Lecture')], max_length=100)),
                ('class_room', models.CharField(max_length=200)),
                ('lesson_name', models.CharField(max_length=200)),
                ('professor', models.CharField(max_length=200)),
                ('number_of_weeks', models.CharField(max_length=50)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset', models.DateField()),
                ('semester', models.CharField(choices=[('Winter', 'Winter'), ('Summer', 'Summer')], max_length=100)),
                ('friday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday_schedule', to='schedule.schedulemodel')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_schedule', to='faculties.groupsmodel')),
                ('monday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday_schedule', to='schedule.schedulemodel')),
                ('saturday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_schema', to='schedule.schedulemodel')),
                ('thursday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_schedule', to='schedule.schedulemodel')),
                ('tuesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_schedule', to='schedule.schedulemodel')),
                ('wednesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_schedule', to='schedule.schedulemodel')),
            ],
        ),
    ]
