# Generated by Django 5.1.2 on 2025-05-25 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100)),
                ('semester', models.CharField(choices=[('Autumn', 'Autumn'), ('Spring', 'Spring')], max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='faculties.groupsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_period', models.CharField(blank=True, choices=[('10:00', '10:00'), ('11:30', '11:30'), ('13:00', '13:00'), ('15:00', '15:00'), ('16:30', '16:30'), ('18:00', '18:00')], max_length=100, null=True)),
                ('end_period', models.CharField(blank=True, choices=[('11:20', '11:20'), ('12:50', '12:50'), ('14:20', '14:20'), ('16:20', '16:20'), ('17:50', '17:50'), ('19:20', '19:20')], max_length=100, null=True)),
                ('week_variance', models.CharField(blank=True, choices=[('Числ.', 'Числ.'), ('Знам.', 'Знам.')], max_length=100, null=True)),
                ('lesson_type', models.CharField(blank=True, choices=[('Практика', 'Практика'), ('Лекция', 'Лекция'), ('Лабораторная', 'Лабораторная')], max_length=100, null=True)),
                ('class_room', models.CharField(max_length=200)),
                ('lesson_name', models.CharField(max_length=200)),
                ('number_of_weeks', models.CharField(max_length=50)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.professormodel')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset', models.DateField()),
                ('end', models.DateField()),
                ('semester', models.CharField(choices=[('Autumn', 'Autumn'), ('Spring', 'Spring')], max_length=100)),
                ('course', models.CharField(choices=[('1st course', '1st course'), ('2nd course', '2nd course'), ('3th course', '3th course'), ('4th course', '4th course'), ('5th course', '5th course')], max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_schedule', to='faculties.groupsmodel')),
                ('schedules', models.ManyToManyField(related_name='semester_schedules', to='schedule.schedulemodel')),
            ],
        ),
    ]
