# Generated by Django 5.1.2 on 2025-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='week_variance',
            field=models.CharField(blank=True, choices=[('Odd', 'Odd'), ('Even', 'Even')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='semesterschedulemodel',
            name='semester',
            field=models.CharField(choices=[('Autumn', 'Autumn'), ('Spring', 'Spring')], max_length=100),
        ),
    ]
