# Generated by Django 5.1.2 on 2025-02-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmodel',
            name='period',
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='end_period',
            field=models.CharField(blank=True, choices=[('11:20', '11:20'), ('12:50', '12:50'), ('14:20', '14:20'), ('16:20', '16:20'), ('17:50', '17:50'), ('19:20', '19:20')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='start_period',
            field=models.CharField(blank=True, choices=[('10:00', '10:00'), ('11:30', '11:30'), ('13:00', '13:00'), ('15:00', '15:00'), ('16:30', '16:30'), ('18:00', '18:00')], max_length=100, null=True),
        ),
    ]
