# Generated by Django 5.1.2 on 2025-05-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='lesson_type',
            field=models.CharField(blank=True, choices=[('Практика', 'Практика'), ('Лекция', 'Лекция')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lessonmodel',
            name='week_variance',
            field=models.CharField(blank=True, choices=[('Числ.', 'Числ.'), ('Знам.', 'Знам.')], max_length=100, null=True),
        ),
    ]
