# Generated by Django 5.1.2 on 2025-05-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_lessonmodel_lesson_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='lesson_type',
            field=models.CharField(blank=True, choices=[('Практика', 'Практика'), ('Лекция', 'Лекция'), ('Лабораторная', 'Лабораторная')], max_length=100, null=True),
        ),
    ]
