# Generated by Django 5.1.2 on 2025-05-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_alter_professormodel_owner'),
        ('schedule', '0003_alter_lessonmodel_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='professor.professormodel'),
        ),
    ]
