# Generated by Django 5.1.2 on 2025-01-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_semesterschedulemodel_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='period',
            field=models.CharField(blank=True, choices=[('10:00-11:20', '10:00-11:20'), ('11:30-12:50', '11:30-12:50'), ('13:00-14:20', '13:00-14:20'), ('15:00-16:20', '15:00-16:20'), ('16:30-17:50', '16:30-17:50'), ('18:00-19:20', '18:00-19:20')], max_length=100, null=True),
        ),
    ]
