# Generated by Django 5.1.2 on 2025-01-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_lessonmodel_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='lesson_type',
            field=models.CharField(blank=True, choices=[('Practice', 'Practice'), ('Lecture', 'Lecture')], max_length=100, null=True),
        ),
    ]
