# Generated by Django 5.1.2 on 2025-05-24 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_alter_professormodel_owner'),
        ('schedule', '0005_alter_lessonmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonmodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lessonmodel',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.professormodel'),
        ),
    ]
