# Generated by Django 5.1.2 on 2024-10-27 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FacultiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.specialtymodel')),
            ],
        ),
    ]
